name: Push
on: [push]

jobs:
  code-quality:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10.0"]
        poetry-version: [1.4.2]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry self add ${{ matrix.poetry-version }}

      - name: Install dependencies
        run: poetry install

      - name: Run black
        run: poetry run black . --check

      - name: Run isort
        run: poetry run isort . --check-only

  publish:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10.0"]
        poetry-version: [1.4.2]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    needs: code-quality
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry self add ${{ matrix.poetry-version }}

      - name: Publish
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          poetry config pypi-token.pypi $PYPI_TOKEN
          poetry publish --build
